<?php
/****
* Copyright 2007 Thomas Welfley and Greg Allard
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*     http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
****/
/**
*	This file is for outputting get handler errors.
*
*	Author: Thomas Welfley
*	Date: 3 / 25 / 2007
*	Version: 0.0.3
*
*	Parameters:	action - specifies which get handler to output errors for. If not specified, key will output errors for any submitted get handler.
*				id - used to specify what you want the id of the printed list to be
*				class - used to specify what you want the class of the printed list to be.
*	container tag: no
*	Special notes: The or operator, "||", can be used inside the value for "action" to allow a developer to specify multiple actions.
*	Example 1:
*	<cyte:get_errors action="login" /> 
*	Example 2:
* 	<cyte:get_errors action="login||search||contact_action" />
*/
	
class get_errors extends key {
	
	public $action;					// List of actions to output errors for.
	public $class;					// html class attribute
	public $id;						// html id attribute
		
	private $action_list;			// Array of actions to output error messages for.
	private $error_messages;		// An array of error messages generated by the get_handler that just executed.	
	private $executed_get_handler;	// The get handler the just executed
	
	function check_attributes() {
		# Check if action was specified, and if it was, split it apart by  ||
		if(!isset($this->action) || $this->action == '') {
			$this->action_list = array();
		} else {
			$this->action_list = explode('||', $this->action);
		}
		
		# Setup class	
		if(trim($this->class) != '') {
			$this->class = ' class="'.$this->class.'"';
		}
		
		# Setup id	
		if(trim($this->id) != '') {
			$this->id = ' id="'.$this->id.'"';
		}
		
		# Get the current list of get error messages
		$this->error_messages = $this->page_request_controller->get_errors;
		
		# Get the get handler that executed - if none, fail.
		if(isset($_GET['action'])) {
			$this->executed_get_handler = $_GET['action'];
		} else {
			$this->failed = TRUE;
			return;
		}
		
		# Fail if there were no errors		
		if(count($this->error_messages) <= 0) {
			$this->failed = TRUE;
			return;
		}
	}
	
	private function generate_list() {
		$html_output = '';
		
		$html_output .= '<ul'.$this->id.$this->class.'>'."\n";
		
		foreach($this->error_messages as $error) {
			$html_output .= "\t".'<li>'.$error.'</li>'."\n";
		}	

		$html_output .= '</ul>';
		
		return $html_output;
	}
	
	function display() {
		if(!$this->failed) {
			if(in_array($this->executed_get_handler, $this->action_list) || count($this->action_list) == 0) {
				return $this->generate_list();
			}
			
			return '';
		}
	}
	
}
?>