<?php
/****
* Copyright 2007 Thomas Welfley and Greg Allard
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*     http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
****/
/**
*	This file is for outputting log in errors
*	
*	Author: Greg Allard
*	Date: 6/12/7
*	Version: 0.0.1
*
*	Parameters:	
*				id - used to specify what you want the id of the printed list to be
*				class - used to specify what you want the class of the printed list to be.
*/
	
class login_errors extends key  {
	public $id;
	public $class = 'error';
	
	private $error_messages;		// An array of error messages generated by the post_handler that just executed.
	
	function check_attributes()  {
		# check if anything was posted before trying anything
		//if (is_array($_POST) && count($_POST) > 0)  {
			# Setup class
			if (trim($this->class) != '')  {
				$this->class = ' class="'.$this->class.'"';
			}
			
			# Setup id
			if (trim($this->id) != '')  {
				$this->id = ' id="'.$this->id.'"';
			}
			
			# Get the current list of post error messages
			$this->error_messages = $this->current_user->errors;
		//}
	}
	
	private function generate_list()  {
		$html_output = '';
		
		
		if (is_array($this->error_messages) && count($this->error_messages) > 0)  {
			$html_output .= '<ul'.$this->id.$this->class.'>'."\n";
			foreach ($this->error_messages as $error)  {
				$html_output .= "\t".'<li>'.$error.'</li>'."\n";
			}
			$html_output .= '</ul>';
		}
		
		
		return $html_output;
	}
	
	function display()  {
		return $this->generate_list();
	}
	
}
?>
